GET http://localhost:3000/users/widjesh@satyamholidays.com

GET http://localhost:3000/users/widjesh8@hotmail.com
###
GET http://localhost:3000/users/
###
POST http://localhost:3000/users
###

POST http://localhost:3000/users/login

Content-Type: application/json
{
    "email":"testmail@email.com",
    "password":"Test1234"
}

GET http://localhost:3000/users/
###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "email" : "testmail@email.com",
    "password" : "Test1234",
    "role": "USER"
}
  
###
PUT http://localhost:3000/users/updaterole/testmail@email.com

Content-Type: application/x-www-form-urlencoded
{
    "role" : "USER",
}

###
DELETE http://localhost:3000/users/remove/kalebzenawi@gmail.com
