GET http://localhost:3000/users/widjesh@satyamholidays.com

###

GET http://localhost:3000/users/
###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "email" : "widjesh@satyamholidays.com",
    "password" : "Test12",
    "role": "ADMIN"
}